name: Deploy to Windows Server

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .ssh directory
        run: |
          New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.ssh

      - name: Decode and write SSH private key
        run: |
          $privateKey = "${{ secrets.DEPLOY_KEY_BASE64 }}"
          $bytes = [System.Convert]::FromBase64String($privateKey)
          [System.IO.File]::WriteAllBytes("$env:USERPROFILE\.ssh\id_ed25519", $bytes)
          icacls "$env:USERPROFILE\.ssh\id_ed25519" /inheritance:r /grant:r "$($env:USERNAME):R"

      - name: Zip project
        run: |
          Compress-Archive -Path * -DestinationPath laravel.zip -Force

      - name: Copy zip to remote server via SCP
        run: |
          scp -i "$env:USERPROFILE\.ssh\id_ed25519" -o StrictHostKeyChecking=no laravel.zip ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }}:~

      - name: Unzip on remote server
        run: |
          ssh -i "$env:USERPROFILE\.ssh\id_ed25519" -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }} "powershell -Command Expand-Archive -Path `"$env:USERPROFILE\laravel.zip`" -DestinationPath `\"${{ secrets.REMOTE_PATH }}\"` -Force"
