name: Deploy to Windows Server

on:
  push:
    branches:
      - master   # change to 'main' if your default branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug DEPLOY_KEY_BASE64 secret info
        run: |
          echo "Secret length:"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | wc -c
          echo "Secret start (first 20 chars):"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | head -c 20
          
      - name: Debug DEPLOY_KEY_BASE64 length
        run: |
          echo "Secret length:"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | wc -c

      - name: Set up SSH key
        run: |
          mkdir -p $HOME/.ssh
          # Remove all whitespace (spaces, tabs, newlines, carriage returns)
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | tr -d ' \t\r\n' | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.WINDOWS_HOST }} >> ~/.ssh/known_hosts


