name: Deploy Laravel to IIS on Windowss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current user running the runner
        shell: powershell
        run: whoami

      - name: Check folder permissions on deployment folder
        shell: powershell
        run: icacls "D:\Web\arul\testing"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --ignore-platform-req=ext-fileinfo

      - name: Copy files to IIS folder
        shell: powershell
        run: |
          $source = "${{ github.workspace }}"
          $destination = "D:\Web\arul\testing"
          robocopy $source $destination /MIR /XD .git node_modules vendor tests .github /XF .env
          $code = $LASTEXITCODE
          if ($code -le 3) {
            Write-Host "Robocopy completed successfully with exit code $code"
            exit 0
          } else {
            Write-Error "Robocopy failed with exit code $code"
            exit $code
          }

      - name: Set permissions for Laravel storage and cache folders
        shell: powershell
        run: |
          $laravelPath = "D:\Web\arul\testing"
          icacls "$laravelPath\storage" /grant "IIS_IUSRS:(OI)(CI)F" /T
          icacls "$laravelPath\bootstrap\cache" /grant "IIS_IUSRS:(OI)(CI)F" /T

      - name: Laravel config/cache optimization
        shell: powershell
        run: |
          cd D:\Web\arul\testing
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache