name: Deploy Laravel to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh"
          $key = "${{ secrets.DEPLOY_KEY_BASE64 }}"
          $key | Out-File -Encoding ascii "$env:USERPROFILE\.ssh\id_ed25519"
          icacls "$env:USERPROFILE\.ssh\id_ed25519" /inheritance:r /grant:r "$($env:USERNAME):(R)"
        shell: pwsh

      - name: Zip Laravel Project
        run: Compress-Archive -Path * -DestinationPath laravel.zip
        shell: pwsh

      - name: Copy zip to Windows server
        run: |
          scp -i "$env:USERPROFILE\.ssh\id_ed25519" -P 2222 -o StrictHostKeyChecking=no laravel.zip ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }}:~/
        shell: pwsh

      - name: Unzip on remote server
        run: |
          ssh -i "$env:USERPROFILE\.ssh\id_ed25519" -P 2222 -o StrictHostKeyChecking=no ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }} "powershell -Command Expand-Archive -Path '$HOME\laravel.zip' -DestinationPath '${{ secrets.REMOTE_PATH }}' -Force"
        shell: pwsh
