name: Deploy to Windows Server

on:
  push:
    branches:
      - master   # change to 'main' if your default branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug DEPLOY_KEY_BASE64 secret info
        run: |
          echo "Secret length:"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | wc -c
          echo "Secret start (first 20 chars):"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | head -c 20
          
      - name: Debug DEPLOY_KEY_BASE64 length
        run: |
          echo "Secret length:"
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | wc -c

      - name: Test mkdir
        run: |
          echo "HOME is $HOME"
          mkdir -p $HOME/.ssh
          ls -ld $HOME
          ls -ld $HOME/.ssh || echo ".ssh folder not found"


