name: Deploy Laravel to IIS on Windowss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --ignore-platform-req=ext-fileinfo --no-dev --optimize-autoloader

      - name: Copy updated files to IIS folder (no vendor, .env, etc.)
        shell: powershell
        run: |
          $source = "${{ github.workspace }}"
          $destination = "D:\Web\arul\testing"
          robocopy $source $destination /MIR /XD .git node_modules vendor tests .github /XF .env
          $code = $LASTEXITCODE
          if ($code -le 3) {
            Write-Host "Robocopy completed successfully with exit code $code"
            exit 0
          } else {
            Write-Error "Robocopy failed with exit code $code"
            exit $code
          }

      - name: Set folder permissions for NETWORK SERVICE
        shell: powershell
        run: |
          $folder = "D:\Web\arul\testing"
          icacls $folder /grant "NT AUTHORITY\NETWORK SERVICE:(OI)(CI)F" /T /C
          
      - name: Debug whoami and check permissions
        shell: powershell
        run: |
          whoami
          icacls "D:\Web\arul\testing"
          icacls "D:\Web\arul\testing\storage"
          icacls "D:\Web\arul\testing\bootstrap\cache"

      - name: Fix permissions on Laravel writable folders
        shell: powershell
        run: |
          $folder = "D:\Web\arul\testing"
          icacls "$folder" /grant "NT AUTHORITY\NETWORK SERVICE:(OI)(CI)F" /T /C
          icacls "$folder\storage" /grant "NT AUTHORITY\NETWORK SERVICE:(OI)(CI)F" /T /C
          icacls "$folder\bootstrap\cache" /grant "NT AUTHORITY\NETWORK SERVICE:(OI)(CI)F" /T /C
    
      - name: Set folder permissions
        shell: powershell
        run: |
          $folder = "D:\Web\arul\testing"
          $user = "pmg-ebizwebserv\arul.kumar"  # Replace with actual whoami output
          $rule = "`"$user`":(OI)(CI)F"
          icacls $folder /grant $rule /T

      - name: Set folder permissions
        shell: powershell
        run: |
          $folder = "D:\Web\arul\testing"
          icacls $folder /grant "*S-1-1-0:(OI)(CI)F" /T
          
      - name: Laravel setup - key generate (if needed)
        shell: powershell
        run: |
          $path = "D:\Web\arul\testing"
          Push-Location $path
          if (!(Test-Path ".env")) {
            Copy-Item ".env.example" ".env"
            php artisan key:generate
          }
          Pop-Location
          
      - name: Run Laravel migrations (optional)
        shell: powershell
        run: |
          cd "D:\Web\arul\testing"
          php artisan migrate --force

      - name: Laravel config/cache optimization
        shell: powershell
        run: |
          cd "D:\Web\arul\testing"
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
