name: Deploy to IIS on Windows

on:
  push:
    branches:
      - master  # or your deployment branchh

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        shell: powershell
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy Files to IIS Folder
        shell: powershell
        run: |
          $source = "${{ github.workspace }}"
          $destination = "D:\Web1\arul\testing"  # <- Change to your IIS folder
          robocopy $source $destination /MIR /XD .git node_modules tests /XF .env
