name: Deploy Laravel to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH folder
        run: |
          New-Item -ItemType Directory -Path $env:USERPROFILE\.ssh -Force

      - name: Add private key
        run: |
          $key = "${{ secrets.DEPLOY_KEY }}" -replace "`r`n", "`n"
          $keyBytes = [System.Text.Encoding]::UTF8.GetBytes($key)
          [System.IO.File]::WriteAllBytes("$env:USERPROFILE\.ssh\id_ed25519", $keyBytes)
          icacls "$env:USERPROFILE\.ssh\id_ed25519" /inheritance:r
          icacls "$env:USERPROFILE\.ssh\id_ed25519" /grant:r "$($env:USERNAME):(R)"

      - name: Zip project files
        run: |
          Compress-Archive -Path * -DestinationPath laravel.zip -Force

      - name: Copy zip to Windows server
        run: |
          scp.exe -i $env:USERPROFILE\.ssh\id_ed25519 -P 2222 laravel.zip ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }}:~

      - name: Unzip on Windows server
        run: |
          ssh.exe -i $env:USERPROFILE\.ssh\id_ed25519 -p 2222 ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }} "powershell -Command Expand-Archive -Path '~/laravel.zip' -DestinationPath '${{ secrets.REMOTE_PATH }}' -Force"
