name: Deploy Laravel to IIS on Windows

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --ignore-platform-req=ext-fileinfo --no-dev --optimize-autoloader

      - name: Copy updated files to IIS folder (no vendor, .env, etc.)
        shell: powershell
        run: |
          $source = "${{ github.workspace }}"
          $destination = "D:\Web\arul\testing"
          robocopy $source $destination /E /XO /XD .git node_modules vendor tests .github /XF .env

      - name: Set folder permissions
        shell: powershell
        run: |
          $folder = "D:\Web\arul\testing"
          $user = "$($env:USERDOMAIN)\$($env:USERNAME)"
          icacls $folder /grant "$user:(OI)(CI)F" /T

      - name: Laravel setup - key generate (if needed)
        shell: powershell
        run: |
          cd "D:\Web\arul\testing"
          if (!(Test-Path ".env")) {
            Copy-Item ".env.example" ".env"
            php artisan key:generate
          }

      - name: Run Laravel migrations (optional)
        shell: powershell
        run: |
          cd "D:\Web\arul\testing"
          php artisan migrate --force

      - name: Laravel config/cache optimization
        shell: powershell
        run: |
          cd "D:\Web\arul\testing"
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
